// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

class PendingOtpMessage {
  PendingOtpMessage({
    required this.id,
    required this.status,
    this.channel,
    required this.maskedRecipient,
    required this.codeLength,
    required this.expiresAt,
    this.resendAvailableAt,
    this.handoffUrl,
  });

  String id;

  /// `pending`, `approved`, `failed`, `expired`, or `unknown` for a status this build cannot name.
  String status;

  /// Null until routing has picked a channel.
  String? channel;

  String maskedRecipient;

  int codeLength;

  String expiresAt;

  String? resendAvailableAt;

  /// WhatsApp only: the link the user opens to be sent the code.
  String? handoffUrl;

  List<Object?> _toList() {
    return <Object?>[
      id,
      status,
      channel,
      maskedRecipient,
      codeLength,
      expiresAt,
      resendAvailableAt,
      handoffUrl,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PendingOtpMessage decode(Object result) {
    result as List<Object?>;
    return PendingOtpMessage(
      id: result[0]! as String,
      status: result[1]! as String,
      channel: result[2] as String?,
      maskedRecipient: result[3]! as String,
      codeLength: result[4]! as int,
      expiresAt: result[5]! as String,
      resendAvailableAt: result[6] as String?,
      handoffUrl: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PendingOtpMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) &&
        _deepEquals(status, other.status) &&
        _deepEquals(channel, other.channel) &&
        _deepEquals(maskedRecipient, other.maskedRecipient) &&
        _deepEquals(codeLength, other.codeLength) &&
        _deepEquals(expiresAt, other.expiresAt) &&
        _deepEquals(resendAvailableAt, other.resendAvailableAt) &&
        _deepEquals(handoffUrl, other.handoffUrl);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PendingOtpMessage(id: $id, status: $status, channel: $channel, maskedRecipient: $maskedRecipient, codeLength: $codeLength, expiresAt: $expiresAt, resendAvailableAt: $resendAvailableAt, handoffUrl: $handoffUrl)';
  }
}

class VerificationMessage {
  VerificationMessage({required this.otpId, required this.token, required this.tokenExpiresAt});

  String otpId;

  String token;

  String tokenExpiresAt;

  List<Object?> _toList() {
    return <Object?>[otpId, token, tokenExpiresAt];
  }

  Object encode() {
    return _toList();
  }

  static VerificationMessage decode(Object result) {
    result as List<Object?>;
    return VerificationMessage(
      otpId: result[0]! as String,
      token: result[1]! as String,
      tokenExpiresAt: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VerificationMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(otpId, other.otpId) &&
        _deepEquals(token, other.token) &&
        _deepEquals(tokenExpiresAt, other.tokenExpiresAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VerificationMessage(otpId: $otpId, token: $token, tokenExpiresAt: $tokenExpiresAt)';
  }
}

class InterruptedMessage {
  InterruptedMessage({required this.otpId, required this.expiresAt, this.locale});

  String otpId;

  String expiresAt;

  String? locale;

  List<Object?> _toList() {
    return <Object?>[otpId, expiresAt, locale];
  }

  Object encode() {
    return _toList();
  }

  static InterruptedMessage decode(Object result) {
    result as List<Object?>;
    return InterruptedMessage(
      otpId: result[0]! as String,
      expiresAt: result[1]! as String,
      locale: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! InterruptedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(otpId, other.otpId) &&
        _deepEquals(expiresAt, other.expiresAt) &&
        _deepEquals(locale, other.locale);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'InterruptedMessage(otpId: $otpId, expiresAt: $expiresAt, locale: $locale)';
  }
}

class CodeSubmissionMessage {
  CodeSubmissionMessage({this.verification, this.attemptsRemaining, this.reason});

  /// Present when the code matched. The token is the only part your backend may trust.
  VerificationMessage? verification;

  /// Set when the code did not match, and null once the verification is resolved.
  int? attemptsRemaining;

  /// `incorrectCode`, `expired`, `noAttemptsLeft`, or `unknown`. Null when the code matched.
  String? reason;

  List<Object?> _toList() {
    return <Object?>[verification, attemptsRemaining, reason];
  }

  Object encode() {
    return _toList();
  }

  static CodeSubmissionMessage decode(Object result) {
    result as List<Object?>;
    return CodeSubmissionMessage(
      verification: result[0] as VerificationMessage?,
      attemptsRemaining: result[1] as int?,
      reason: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CodeSubmissionMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(verification, other.verification) &&
        _deepEquals(attemptsRemaining, other.attemptsRemaining) &&
        _deepEquals(reason, other.reason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CodeSubmissionMessage(verification: $verification, attemptsRemaining: $attemptsRemaining, reason: $reason)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PendingOtpMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is VerificationMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is InterruptedMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CodeSubmissionMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PendingOtpMessage.decode(readValue(buffer)!);
      case 130:
        return VerificationMessage.decode(readValue(buffer)!);
      case 131:
        return InterruptedMessage.decode(readValue(buffer)!);
      case 132:
        return CodeSubmissionMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class OtpHostApi {
  /// Constructor for [OtpHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  OtpHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
          ? '.$messageChannelSuffix'
          : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> configure(String publishableKey, String? baseUrl) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.configure$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      publishableKey,
      baseUrl,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(pigeonVar_replyList, pigeonVar_channelName, isNullValid: true);
  }

  /// Presents the code screen for a recipient your own screen already collected.
  Future<VerificationMessage> verify(String recipient, String? locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.verify$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      recipient,
      locale,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VerificationMessage;
  }

  /// Presents the recipient screen, then the code screen. `kind` is `phone` or `email`.
  Future<VerificationMessage> verifyCollecting(String kind, String? locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.verifyCollecting$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[kind, locale]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VerificationMessage;
  }

  /// Presents the code screen for a verification left in flight, if there is one.
  ///
  /// Resolves with null when there was nothing to resume, which includes a verification that has
  /// expired or been answered in the meantime, and when the user closes the screen.
  Future<VerificationMessage?> resumeInterrupted() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.resumeInterrupted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as VerificationMessage?;
  }

  Future<PendingOtpMessage> start(String recipient, String? locale) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[
      recipient,
      locale,
    ]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PendingOtpMessage;
  }

  Future<CodeSubmissionMessage> submit(String otpId, String code) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.submit$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[otpId, code]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as CodeSubmissionMessage;
  }

  Future<PendingOtpMessage> resend(String otpId, String? channel) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.resend$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[otpId, channel]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PendingOtpMessage;
  }

  Future<PendingOtpMessage> resume(String otpId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.resume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[otpId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PendingOtpMessage;
  }

  /// The verification this install left in flight, or null. Reads what the device kept and makes
  /// no request, so it is safe to call on launch.
  ///
  /// Read from the native SDK's own store rather than from Dart, so it survives the process being
  /// killed while the user was away in WhatsApp receiving their code. Without it an app would have
  /// to persist the id itself to be able to call `resume`.
  Future<InterruptedMessage?> interrupted() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.otp_flutter.OtpHostApi.interrupted$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as InterruptedMessage?;
  }
}
