// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct PendingOtpMessage: Hashable, CustomStringConvertible {
  var id: String
  /// `pending`, `approved`, `failed`, `expired`, or `unknown` for a status this build cannot name.
  var status: String
  /// Null until routing has picked a channel.
  var channel: String? = nil
  var maskedRecipient: String
  var codeLength: Int64
  var expiresAt: String
  var resendAvailableAt: String? = nil
  /// WhatsApp only: the link the user opens to be sent the code.
  var handoffUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PendingOtpMessage? {
    let id = pigeonVar_list[0] as! String
    let status = pigeonVar_list[1] as! String
    let channel: String? = nilOrValue(pigeonVar_list[2])
    let maskedRecipient = pigeonVar_list[3] as! String
    let codeLength = pigeonVar_list[4] as! Int64
    let expiresAt = pigeonVar_list[5] as! String
    let resendAvailableAt: String? = nilOrValue(pigeonVar_list[6])
    let handoffUrl: String? = nilOrValue(pigeonVar_list[7])

    return PendingOtpMessage(
      id: id,
      status: status,
      channel: channel,
      maskedRecipient: maskedRecipient,
      codeLength: codeLength,
      expiresAt: expiresAt,
      resendAvailableAt: resendAvailableAt,
      handoffUrl: handoffUrl
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      status,
      channel,
      maskedRecipient,
      codeLength,
      expiresAt,
      resendAvailableAt,
      handoffUrl,
    ]
  }
  static func == (lhs: PendingOtpMessage, rhs: PendingOtpMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.id, rhs.id) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.channel, rhs.channel) && MessagesPigeonInternal.deepEquals(lhs.maskedRecipient, rhs.maskedRecipient) && MessagesPigeonInternal.deepEquals(lhs.codeLength, rhs.codeLength) && MessagesPigeonInternal.deepEquals(lhs.expiresAt, rhs.expiresAt) && MessagesPigeonInternal.deepEquals(lhs.resendAvailableAt, rhs.resendAvailableAt) && MessagesPigeonInternal.deepEquals(lhs.handoffUrl, rhs.handoffUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PendingOtpMessage")
    MessagesPigeonInternal.deepHash(value: id, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: channel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maskedRecipient, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: codeLength, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expiresAt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resendAvailableAt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: handoffUrl, hasher: &hasher)
  }

  public var description: String {
    return "PendingOtpMessage(id: \(String(describing: id)), status: \(String(describing: status)), channel: \(String(describing: channel)), maskedRecipient: \(String(describing: maskedRecipient)), codeLength: \(String(describing: codeLength)), expiresAt: \(String(describing: expiresAt)), resendAvailableAt: \(String(describing: resendAvailableAt)), handoffUrl: \(String(describing: handoffUrl)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VerificationMessage: Hashable, CustomStringConvertible {
  var otpId: String
  var token: String
  var tokenExpiresAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VerificationMessage? {
    let otpId = pigeonVar_list[0] as! String
    let token = pigeonVar_list[1] as! String
    let tokenExpiresAt = pigeonVar_list[2] as! String

    return VerificationMessage(
      otpId: otpId,
      token: token,
      tokenExpiresAt: tokenExpiresAt
    )
  }
  func toList() -> [Any?] {
    return [
      otpId,
      token,
      tokenExpiresAt,
    ]
  }
  static func == (lhs: VerificationMessage, rhs: VerificationMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.otpId, rhs.otpId) && MessagesPigeonInternal.deepEquals(lhs.token, rhs.token) && MessagesPigeonInternal.deepEquals(lhs.tokenExpiresAt, rhs.tokenExpiresAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VerificationMessage")
    MessagesPigeonInternal.deepHash(value: otpId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: token, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: tokenExpiresAt, hasher: &hasher)
  }

  public var description: String {
    return "VerificationMessage(otpId: \(String(describing: otpId)), token: \(String(describing: token)), tokenExpiresAt: \(String(describing: tokenExpiresAt)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct InterruptedMessage: Hashable, CustomStringConvertible {
  var otpId: String
  var expiresAt: String
  var locale: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> InterruptedMessage? {
    let otpId = pigeonVar_list[0] as! String
    let expiresAt = pigeonVar_list[1] as! String
    let locale: String? = nilOrValue(pigeonVar_list[2])

    return InterruptedMessage(
      otpId: otpId,
      expiresAt: expiresAt,
      locale: locale
    )
  }
  func toList() -> [Any?] {
    return [
      otpId,
      expiresAt,
      locale,
    ]
  }
  static func == (lhs: InterruptedMessage, rhs: InterruptedMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.otpId, rhs.otpId) && MessagesPigeonInternal.deepEquals(lhs.expiresAt, rhs.expiresAt) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("InterruptedMessage")
    MessagesPigeonInternal.deepHash(value: otpId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: expiresAt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
  }

  public var description: String {
    return "InterruptedMessage(otpId: \(String(describing: otpId)), expiresAt: \(String(describing: expiresAt)), locale: \(String(describing: locale)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CodeSubmissionMessage: Hashable, CustomStringConvertible {
  /// Present when the code matched. The token is the only part your backend may trust.
  var verification: VerificationMessage? = nil
  /// Set when the code did not match, and null once the verification is resolved.
  var attemptsRemaining: Int64? = nil
  /// `incorrectCode`, `expired`, `noAttemptsLeft`, or `unknown`. Null when the code matched.
  var reason: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CodeSubmissionMessage? {
    let verification: VerificationMessage? = nilOrValue(pigeonVar_list[0])
    let attemptsRemaining: Int64? = nilOrValue(pigeonVar_list[1])
    let reason: String? = nilOrValue(pigeonVar_list[2])

    return CodeSubmissionMessage(
      verification: verification,
      attemptsRemaining: attemptsRemaining,
      reason: reason
    )
  }
  func toList() -> [Any?] {
    return [
      verification,
      attemptsRemaining,
      reason,
    ]
  }
  static func == (lhs: CodeSubmissionMessage, rhs: CodeSubmissionMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.verification, rhs.verification) && MessagesPigeonInternal.deepEquals(lhs.attemptsRemaining, rhs.attemptsRemaining) && MessagesPigeonInternal.deepEquals(lhs.reason, rhs.reason)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CodeSubmissionMessage")
    MessagesPigeonInternal.deepHash(value: verification, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attemptsRemaining, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: reason, hasher: &hasher)
  }

  public var description: String {
    return "CodeSubmissionMessage(verification: \(String(describing: verification)), attemptsRemaining: \(String(describing: attemptsRemaining)), reason: \(String(describing: reason)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PendingOtpMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return VerificationMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return InterruptedMessage.fromList(self.readValue() as! [Any?])
    case 132:
      return CodeSubmissionMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PendingOtpMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VerificationMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? InterruptedMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CodeSubmissionMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OtpHostApi {
  func configure(publishableKey: String, baseUrl: String?) async throws
  /// Presents the code screen for a recipient your own screen already collected.
  func verify(recipient: String, locale: String?) async throws -> VerificationMessage
  /// Presents the recipient screen, then the code screen. `kind` is `phone` or `email`.
  func verifyCollecting(kind: String, locale: String?) async throws -> VerificationMessage
  /// Presents the code screen for a verification left in flight, if there is one.
  ///
  /// Resolves with null when there was nothing to resume, which includes a verification that has
  /// expired or been answered in the meantime, and when the user closes the screen.
  func resumeInterrupted() async throws -> VerificationMessage?
  func start(recipient: String, locale: String?) async throws -> PendingOtpMessage
  func submit(otpId: String, code: String) async throws -> CodeSubmissionMessage
  func resend(otpId: String, channel: String?) async throws -> PendingOtpMessage
  func resume(otpId: String) async throws -> PendingOtpMessage
  /// The verification this install left in flight, or null. Reads what the device kept and makes
  /// no request, so it is safe to call on launch.
  ///
  /// Read from the native SDK's own store rather than from Dart, so it survives the process being
  /// killed while the user was away in WhatsApp receiving their code. Without it an app would have
  /// to persist the id itself to be able to call `resume`.
  func interrupted() async throws -> InterruptedMessage?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OtpHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `OtpHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OtpHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let publishableKeyArg = args[0] as! String
        let baseUrlArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            try await api.configure(publishableKey: publishableKeyArg, baseUrl: baseUrlArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Presents the code screen for a recipient your own screen already collected.
    let verifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.verify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recipientArg = args[0] as! String
        let localeArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.verify(recipient: recipientArg, locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      verifyChannel.setMessageHandler(nil)
    }
    /// Presents the recipient screen, then the code screen. `kind` is `phone` or `email`.
    let verifyCollectingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.verifyCollecting\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      verifyCollectingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let kindArg = args[0] as! String
        let localeArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.verifyCollecting(kind: kindArg, locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      verifyCollectingChannel.setMessageHandler(nil)
    }
    /// Presents the code screen for a verification left in flight, if there is one.
    ///
    /// Resolves with null when there was nothing to resume, which includes a verification that has
    /// expired or been answered in the meantime, and when the user closes the screen.
    let resumeInterruptedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.resumeInterrupted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeInterruptedChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.resumeInterrupted()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeInterruptedChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recipientArg = args[0] as! String
        let localeArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.start(recipient: recipientArg, locale: localeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let submitChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.submit\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let otpIdArg = args[0] as! String
        let codeArg = args[1] as! String
        Task { @MainActor in
          do {
            let result = try await api.submit(otpId: otpIdArg, code: codeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      submitChannel.setMessageHandler(nil)
    }
    let resendChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.resend\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resendChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let otpIdArg = args[0] as! String
        let channelArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.resend(otpId: otpIdArg, channel: channelArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      resendChannel.setMessageHandler(nil)
    }
    let resumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.resume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let otpIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.resume(otpId: otpIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeChannel.setMessageHandler(nil)
    }
    /// The verification this install left in flight, or null. Reads what the device kept and makes
    /// no request, so it is safe to call on launch.
    ///
    /// Read from the native SDK's own store rather than from Dart, so it survives the process being
    /// killed while the user was away in WhatsApp receiving their code. Without it an app would have
    /// to persist the id itself to be able to call `resume`.
    let interruptedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.otp_flutter.OtpHostApi.interrupted\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      interruptedChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.interrupted()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      interruptedChannel.setMessageHandler(nil)
    }
  }
}
