// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.otp.sdk.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class PendingOtpMessage (
  val id: String,
  /** `pending`, `approved`, `failed`, `expired`, or `unknown` for a status this build cannot name. */
  val status: String,
  /** Null until routing has picked a channel. */
  val channel: String? = null,
  val maskedRecipient: String,
  val codeLength: Long,
  val expiresAt: String,
  val resendAvailableAt: String? = null,
  /** WhatsApp only: the link the user opens to be sent the code. */
  val handoffUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PendingOtpMessage {
      val id = pigeonVar_list[0] as String
      val status = pigeonVar_list[1] as String
      val channel = pigeonVar_list[2] as String?
      val maskedRecipient = pigeonVar_list[3] as String
      val codeLength = pigeonVar_list[4] as Long
      val expiresAt = pigeonVar_list[5] as String
      val resendAvailableAt = pigeonVar_list[6] as String?
      val handoffUrl = pigeonVar_list[7] as String?
      return PendingOtpMessage(id, status, channel, maskedRecipient, codeLength, expiresAt, resendAvailableAt, handoffUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      status,
      channel,
      maskedRecipient,
      codeLength,
      expiresAt,
      resendAvailableAt,
      handoffUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PendingOtpMessage
    return MessagesPigeonUtils.deepEquals(this.id, other.id) && MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.channel, other.channel) && MessagesPigeonUtils.deepEquals(this.maskedRecipient, other.maskedRecipient) && MessagesPigeonUtils.deepEquals(this.codeLength, other.codeLength) && MessagesPigeonUtils.deepEquals(this.expiresAt, other.expiresAt) && MessagesPigeonUtils.deepEquals(this.resendAvailableAt, other.resendAvailableAt) && MessagesPigeonUtils.deepEquals(this.handoffUrl, other.handoffUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.id)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.channel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maskedRecipient)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.codeLength)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expiresAt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.resendAvailableAt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.handoffUrl)
    return result
  }
  override fun toString(): String {
    return "PendingOtpMessage(id=$id, status=$status, channel=$channel, maskedRecipient=$maskedRecipient, codeLength=$codeLength, expiresAt=$expiresAt, resendAvailableAt=$resendAvailableAt, handoffUrl=$handoffUrl)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VerificationMessage (
  val otpId: String,
  val token: String,
  val tokenExpiresAt: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VerificationMessage {
      val otpId = pigeonVar_list[0] as String
      val token = pigeonVar_list[1] as String
      val tokenExpiresAt = pigeonVar_list[2] as String
      return VerificationMessage(otpId, token, tokenExpiresAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      otpId,
      token,
      tokenExpiresAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VerificationMessage
    return MessagesPigeonUtils.deepEquals(this.otpId, other.otpId) && MessagesPigeonUtils.deepEquals(this.token, other.token) && MessagesPigeonUtils.deepEquals(this.tokenExpiresAt, other.tokenExpiresAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.otpId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.token)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.tokenExpiresAt)
    return result
  }
  override fun toString(): String {
    return "VerificationMessage(otpId=$otpId, token=$token, tokenExpiresAt=$tokenExpiresAt)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InterruptedMessage (
  val otpId: String,
  val expiresAt: String,
  val locale: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InterruptedMessage {
      val otpId = pigeonVar_list[0] as String
      val expiresAt = pigeonVar_list[1] as String
      val locale = pigeonVar_list[2] as String?
      return InterruptedMessage(otpId, expiresAt, locale)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      otpId,
      expiresAt,
      locale,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InterruptedMessage
    return MessagesPigeonUtils.deepEquals(this.otpId, other.otpId) && MessagesPigeonUtils.deepEquals(this.expiresAt, other.expiresAt) && MessagesPigeonUtils.deepEquals(this.locale, other.locale)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.otpId)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.expiresAt)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.locale)
    return result
  }
  override fun toString(): String {
    return "InterruptedMessage(otpId=$otpId, expiresAt=$expiresAt, locale=$locale)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CodeSubmissionMessage (
  /** Present when the code matched. The token is the only part your backend may trust. */
  val verification: VerificationMessage? = null,
  /** Set when the code did not match, and null once the verification is resolved. */
  val attemptsRemaining: Long? = null,
  /** `incorrectCode`, `expired`, `noAttemptsLeft`, or `unknown`. Null when the code matched. */
  val reason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CodeSubmissionMessage {
      val verification = pigeonVar_list[0] as VerificationMessage?
      val attemptsRemaining = pigeonVar_list[1] as Long?
      val reason = pigeonVar_list[2] as String?
      return CodeSubmissionMessage(verification, attemptsRemaining, reason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verification,
      attemptsRemaining,
      reason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CodeSubmissionMessage
    return MessagesPigeonUtils.deepEquals(this.verification, other.verification) && MessagesPigeonUtils.deepEquals(this.attemptsRemaining, other.attemptsRemaining) && MessagesPigeonUtils.deepEquals(this.reason, other.reason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.verification)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attemptsRemaining)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.reason)
    return result
  }
  override fun toString(): String {
    return "CodeSubmissionMessage(verification=$verification, attemptsRemaining=$attemptsRemaining, reason=$reason)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PendingOtpMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VerificationMessage.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InterruptedMessage.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CodeSubmissionMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PendingOtpMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VerificationMessage -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is InterruptedMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is CodeSubmissionMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface OtpHostApi {
  suspend fun configure(publishableKey: String, baseUrl: String?)
  /** Presents the code screen for a recipient your own screen already collected. */
  suspend fun verify(recipient: String, locale: String?): VerificationMessage
  /** Presents the recipient screen, then the code screen. `kind` is `phone` or `email`. */
  suspend fun verifyCollecting(kind: String, locale: String?): VerificationMessage
  /**
   * Presents the code screen for a verification left in flight, if there is one.
   *
   * Resolves with null when there was nothing to resume, which includes a verification that has
   * expired or been answered in the meantime, and when the user closes the screen.
   */
  suspend fun resumeInterrupted(): VerificationMessage?
  suspend fun start(recipient: String, locale: String?): PendingOtpMessage
  suspend fun submit(otpId: String, code: String): CodeSubmissionMessage
  suspend fun resend(otpId: String, channel: String?): PendingOtpMessage
  suspend fun resume(otpId: String): PendingOtpMessage
  /**
   * The verification this install left in flight, or null. Reads what the device kept and makes
   * no request, so it is safe to call on launch.
   *
   * Read from the native SDK's own store rather than from Dart, so it survives the process being
   * killed while the user was away in WhatsApp receiving their code. Without it an app would have
   * to persist the id itself to be able to call `resume`.
   */
  suspend fun interrupted(): InterruptedMessage?

  companion object {
    /** The codec used by OtpHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `OtpHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: OtpHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val publishableKeyArg = args[0] as String
            val baseUrlArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.configure(publishableKeyArg, baseUrlArg)
                listOf(null)
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.verify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recipientArg = args[0] as String
            val localeArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.verify(recipientArg, localeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.verifyCollecting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kindArg = args[0] as String
            val localeArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.verifyCollecting(kindArg, localeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.resumeInterrupted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.resumeInterrupted())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val recipientArg = args[0] as String
            val localeArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.start(recipientArg, localeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.submit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val otpIdArg = args[0] as String
            val codeArg = args[1] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.submit(otpIdArg, codeArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.resend$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val otpIdArg = args[0] as String
            val channelArg = args[1] as String?
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.resend(otpIdArg, channelArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.resume$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val otpIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.resume(otpIdArg))
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.otp_flutter.OtpHostApi.interrupted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.interrupted())
              } catch (exception: Throwable) {
                MessagesPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
